// Read-only assembly of a CLAUDE.md vault-navigation guide.
//
// When the user runs BOTH the Obsidian Vault add-on AND the Claude Code add-on,
// the Tome-of-Lore summary card offers a one-click "Generate CLAUDE.md for your
// vault". This module builds that guide's content from the vault's ACTUAL
// structure (folders, entity-type counts, frontmatter conventions, alias
// usage) so that the user's own Claude Code sessions — or any AI tool — can
// navigate the vault efficiently.
//
// The guide documents structure only: folder names, field names, and counts.
// It never copies note BODY content, so it can't leak private campaign detail.
//
// STRICTLY READ-ONLY: this module never writes into the vault. The actual file
// write lives in vaultTools.ts (writeVaultClaudeMd) — the documented home for
// the add-on's sanctioned vault writes — so this module stays under the
// readonly-guard test alongside vaultAdapter.ts / vaultKb.ts.

import { promises as fs } from 'node:fs'
import path from 'node:path'
import {
  buildObsidianAliasIndex,
  walkVaultNotes,
  VAULT_EXCLUDE_DIRS,
  VAULT_EXCLUDE_FILES,
} from './vaultAdapter.js'

export const VAULT_CLAUDE_MD_FILENAME = 'CLAUDE.md'

const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n/

type VaultStructure = {
  noteCount: number
  /** Top-level folder → note count, sorted by name. `(root)` for vault-root notes. */
  folders: Array<{ name: string; count: number }>
  /** Frontmatter keys observed across notes, most-common first. */
  frontmatterKeys: string[]
  /** How many notes declare an `aliases:` field. */
  aliasNoteCount: number
}

/** One read-only walk gathering the structural stats the guide reports.
 *  Reads only frontmatter fences — never note bodies. */
async function scanVaultStructure(vaultPath: string): Promise<VaultStructure> {
  const folderCounts = new Map<string, number>()
  const keyCounts = new Map<string, number>()
  let noteCount = 0
  let aliasNoteCount = 0
  for await (const { absPath, relPath } of walkVaultNotes(vaultPath)) {
    noteCount++
    const top = relPath.includes('/') ? relPath.slice(0, relPath.indexOf('/')) : '(root)'
    folderCounts.set(top, (folderCounts.get(top) ?? 0) + 1)
    let raw: string
    try {
      raw = await fs.readFile(absPath, 'utf8')
    } catch {
      continue
    }
    const fm = raw.match(FRONTMATTER_RE)
    if (!fm) continue
    let hasAlias = false
    for (const line of fm[1].split(/\r?\n/)) {
      const m = line.match(/^([A-Za-z_][\w-]*):/)
      if (!m) continue
      const key = m[1].toLowerCase()
      keyCounts.set(key, (keyCounts.get(key) ?? 0) + 1)
      if (key === 'aliases') hasAlias = true
    }
    if (hasAlias) aliasNoteCount++
  }
  const folders = [...folderCounts.entries()]
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => a.name.localeCompare(b.name))
  const frontmatterKeys = [...keyCounts.entries()].sort((a, b) => b[1] - a[1]).map(([k]) => k)
  return { noteCount, folders, frontmatterKeys, aliasNoteCount }
}

/** Build the CLAUDE.md navigation guide for a vault. Pure read — returns the
 *  markdown string; the caller decides whether/where to write it. */
export async function buildVaultClaudeMd(vaultPath: string): Promise<string> {
  const [idx, struct] = await Promise.all([
    buildObsidianAliasIndex(vaultPath),
    scanVaultStructure(vaultPath),
  ])
  const entityTotal = Object.keys(idx.index.byEntity).length
  const sourceLabel =
    idx.source === 'entity-index'
      ? 'curated `_system/entity-index.json`'
      : 'note frontmatter (`type:` / `aliases:`)'

  const lines: string[] = []
  lines.push('# Vault navigation guide')
  lines.push('')
  lines.push(
    '_Generated by Tusk\'s Tomes. This file documents the structure of this Obsidian ' +
      'vault so AI tools (e.g. Claude Code) can navigate it efficiently. Tusk\'s Tomes ' +
      'itself reads this vault **strictly read-only** — the only files it ever writes are ' +
      'this guide and an optional `graphify-out/` map, and only on explicit request._',
  )
  lines.push('')

  // Zero-content guidance rather than a misleading empty guide.
  if (struct.noteCount === 0) {
    lines.push('## Overview')
    lines.push('')
    lines.push(
      'No notes were found in this vault yet. Add one Markdown note per entity with ' +
        'YAML frontmatter (`type:` and `aliases:`) so grounding can map names.',
    )
    lines.push('')
    appendUsageSection(lines)
    return lines.join('\n') + '\n'
  }

  lines.push('## Overview')
  lines.push('')
  lines.push(`- Lore entities indexed: **${entityTotal}** (source: ${sourceLabel})`)
  lines.push(`- Notes scanned: **${struct.noteCount}**`)
  lines.push(`- Notes declaring \`aliases:\`: **${struct.aliasNoteCount}** of ${struct.noteCount}`)
  lines.push('')

  if (struct.folders.length > 0) {
    lines.push('## Folders')
    lines.push('')
    for (const f of struct.folders) {
      const label = f.name === '(root)' ? '`/` (vault root)' : `\`${f.name}/\``
      lines.push(`- ${label} — ${f.count} note${f.count === 1 ? '' : 's'}`)
    }
    lines.push('')
  }

  const typeEntries = (Object.entries(idx.index.byType) as Array<[string, string[]]>).filter(
    ([, names]) => names.length > 0,
  )
  if (typeEntries.length > 0) {
    lines.push('## Entity types')
    lines.push('')
    for (const [type, names] of typeEntries) {
      lines.push(`- ${type}: ${names.length}`)
    }
    lines.push('')
  }

  if (struct.frontmatterKeys.length > 0) {
    lines.push('## Frontmatter conventions')
    lines.push('')
    lines.push('Notes carry top-level YAML frontmatter. Observed keys (most common first):')
    lines.push('')
    lines.push(struct.frontmatterKeys.map((k) => `\`${k}\``).join(', '))
    lines.push('')
    lines.push(
      'The highest-value field for grounding is `aliases:` — list each entity\'s ' +
        'nicknames and alternate spellings so transcription errors map to the canonical ' +
        'name (the note title).',
    )
    lines.push('')
  }

  appendUsageSection(lines)
  return lines.join('\n') + '\n'
}

function appendUsageSection(lines: string[]): void {
  lines.push('## How Tusk\'s Tomes reads this vault')
  lines.push('')
  lines.push('- Canonical names come from note titles (filenames).')
  lines.push('- Aliases come from each note\'s `aliases:` frontmatter.')
  lines.push('- Note bodies become the chronicle Knowledge Base (wikilinks flattened to text).')
  lines.push(
    `- Ignored when indexing: ${[...VAULT_EXCLUDE_DIRS]
      .map((d) => `\`${d}/\``)
      .join(', ')}, and root files like ${[...VAULT_EXCLUDE_FILES]
      .map((f) => `\`${f}\``)
      .join(', ')}.`,
  )
}

export type ExistingClaudeMd = {
  present: boolean
  /** A short, bounded preview of the existing file (for a don't-clobber prompt). */
  summary: string | null
  modifiedAt: string | null
}

const PREVIEW_MAX_LINES = 40
const PREVIEW_MAX_BYTES = 4_000

/** Read an existing vault CLAUDE.md (if any) into a bounded preview/summary.
 *  Used to (a) show a don't-clobber confirmation before regenerating and
 *  (b) feed the optional grounding-context toggle. Read-only, size-capped. */
export async function readVaultClaudeMd(vaultPath: string): Promise<ExistingClaudeMd> {
  const abs = joinClaudeMd(vaultPath)
  let raw: string
  let modifiedAt: string | null = null
  try {
    const [content, stat] = await Promise.all([fs.readFile(abs, 'utf8'), fs.stat(abs)])
    raw = content
    modifiedAt = stat.mtime.toISOString()
  } catch {
    return { present: false, summary: null, modifiedAt: null }
  }
  const summary = raw
    .slice(0, PREVIEW_MAX_BYTES)
    .split(/\r?\n/)
    .slice(0, PREVIEW_MAX_LINES)
    .join('\n')
    .trim()
  return { present: true, summary: summary || null, modifiedAt }
}

/** Absolute path to the vault-root CLAUDE.md. Exported so the write helper in
 *  vaultTools.ts and the route resolve the same target. */
export function joinClaudeMd(vaultPath: string): string {
  return path.join(vaultPath, VAULT_CLAUDE_MD_FILENAME)
}
