#!/usr/bin/env node
// Sync docs/ -> the GitHub wiki repo (Tusks-Tomes.wiki.git).
//
// Usage:
//   node scripts/sync-wiki.mjs [--wiki-dir <path>] [--dry-run]
//
// Defaults to a sibling dir ../Tusks-Tomes.wiki. The wiki repo must be
// cloned separately first:
//
//   git clone https://github.com/KochiTusker/Tusks-Tomes.wiki.git ../Tusks-Tomes.wiki
//
// (GitHub creates the wiki repo only after the first wiki page is created
// via the web UI — visit the repo's Wiki tab once if the clone 404s.)
//
// The script:
//   1. Enumerates docs/**/*.md, excluding dev-only and asset-organisation
//      paths (see EXCLUDE_PREFIXES).
//   2. Flattens directories into wiki page names (docs/add-ons/foo.md ->
//      Add-Ons-Foo.md); README.md becomes Home.md.
//   3. Rewrites internal .md links to point at the new flat names, and
//      ../path links to absolute GitHub blob URLs (the wiki repo is
//      separate from the code repo).
//   4. Runs the same per-file OSINT scans the pre-push gate uses
//      (emails, local paths, token shapes). Halts on any finding so the
//      wiki never ships an identifier the public repo wouldn't.
//   5. Writes the result into the wiki dir; the user reviews and
//      commits/pushes manually.

import { readFile, writeFile, readdir, stat, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname, relative, posix, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

import {
  scanLinesForEmails,
  scanLinesForLocalPaths,
  scanLinesForSpeakerNames,
} from "./lib/personal-info-scanner.mjs";
import { scanLinesForTokens } from "./lib/secret-scanner.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const DOCS_DIR = join(REPO_ROOT, "docs");
const PUBLIC_REPO_URL = "https://github.com/KochiTusker/Tusks-Tomes";
const PUBLIC_BLOB_BASE = `${PUBLIC_REPO_URL}/blob/main`;

// docs/security/** is dev-only (release workflow). docs/assets/** is the
// image-organisation note, not a wiki page.
const EXCLUDE_PREFIXES = ["security/", "assets/"];

const GENERATED_MARKER = "<!-- generated by scripts/sync-wiki.mjs — edits will be overwritten on next sync -->";

// ---------- Arg parsing ----------

function parseArgs(argv) {
  const args = { wikiDir: null, dryRun: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--wiki-dir") args.wikiDir = argv[++i];
    else if (a === "--dry-run") args.dryRun = true;
    else if (a === "--help" || a === "-h") {
      console.log("Usage: node scripts/sync-wiki.mjs [--wiki-dir <path>] [--dry-run]");
      process.exit(0);
    } else {
      console.error(`Unknown arg: ${a}`);
      process.exit(2);
    }
  }
  args.wikiDir = resolve(args.wikiDir || join(REPO_ROOT, "..", "Tusks-Tomes.wiki"));
  return args;
}

// ---------- File enumeration ----------

async function walk(dir, relBase = "") {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const abs = join(dir, entry.name);
    const rel = relBase ? posix.join(relBase, entry.name) : entry.name;
    if (entry.isDirectory()) {
      out.push(...(await walk(abs, rel)));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      if (EXCLUDE_PREFIXES.some((p) => rel.startsWith(p))) continue;
      out.push(rel);
    }
  }
  return out;
}

// ---------- Naming ----------

function titleSegment(seg) {
  // Split on hyphens, capitalise each word, rejoin. "add-ons" -> "Add-Ons".
  return seg
    .split("-")
    .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
    .join("-");
}

function wikiNameFor(relPath) {
  const noExt = relPath.replace(/\.md$/i, "");
  const parts = noExt.split("/");
  if (parts.length === 1 && parts[0].toUpperCase() === "README") {
    return "Home.md";
  }
  if (parts[parts.length - 1].toUpperCase() === "README") {
    parts.pop();
  }
  return parts.map(titleSegment).join("-") + ".md";
}

// ---------- Link rewriting ----------

function buildRewriter(renames) {
  // renames: Map<sourceRelPath, wikiFileName>
  // Matches markdown links: ](target) and ](target#hash), where target
  // is anything not containing ) or whitespace.
  const linkRe = /\]\(([^)\s#]+)(#[^)\s]*)?\)/g;

  return function rewrite(content, sourceRel) {
    return content.replace(linkRe, (match, target, hash = "") => {
      if (/^https?:|^mailto:|^#/.test(target)) return match;

      // Resolve target relative to the source file's directory in docs/.
      const sourceDir = posix.dirname(sourceRel);
      const resolved = posix.normalize(
        sourceDir === "." ? target : posix.join(sourceDir, target),
      );

      // Case 1: target lives in docs/ and is in our rename map.
      const mdKey = resolved.endsWith(".md") ? resolved : null;
      if (mdKey && renames.has(mdKey)) {
        const pageName = renames.get(mdKey).replace(/\.md$/, "");
        return `](${pageName}${hash})`;
      }

      // Case 2: target leaves docs/ (starts with .. after normalise).
      //   docs/foo.md links to ../README.md -> normalises to "../README.md"
      //   resolve to repo-root-relative for the GitHub blob URL.
      if (resolved.startsWith("../")) {
        const repoRelative = resolved.replace(/^\.\.\//, "");
        return `](${PUBLIC_BLOB_BASE}/${repoRelative}${hash})`;
      }

      // Case 3: target is inside docs/ but not in our rename map (e.g.
      //   an excluded file, or a broken pre-existing link). Leave as-is
      //   so the user sees it in review.
      return match;
    });
  };
}

// ---------- OSINT scan ----------

function scanContent(file, content) {
  return [
    ...scanLinesForEmails(file, content),
    ...scanLinesForLocalPaths(file, content),
    ...scanLinesForSpeakerNames(file, content),
    ...scanLinesForTokens(file, content),
  ];
}

// ---------- Main ----------

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (!existsSync(DOCS_DIR)) {
    console.error(`docs/ not found at ${DOCS_DIR}`);
    process.exit(1);
  }

  const wikiExists = existsSync(args.wikiDir) && existsSync(join(args.wikiDir, ".git"));
  if (!wikiExists && !args.dryRun) {
    console.error(`Wiki repo not found at ${args.wikiDir}`);
    console.error("");
    console.error("Clone it first (GitHub creates the wiki repo only after the");
    console.error("first wiki page is added via the web UI — if this 404s, open");
    console.error(`${PUBLIC_REPO_URL}/wiki and create any page, then retry):`);
    console.error("");
    console.error(`  git clone ${PUBLIC_REPO_URL}.wiki.git "${args.wikiDir}"`);
    console.error("");
    console.error("Or re-run with --dry-run to preview without writing.");
    process.exit(1);
  }

  const sources = (await walk(DOCS_DIR)).sort();
  if (sources.length === 0) {
    console.error("No .md files found under docs/");
    process.exit(1);
  }

  const renames = new Map(sources.map((s) => [s, wikiNameFor(s)]));

  // Collision check — flattening "add-ons/foo.md" and "Add-Ons/foo.md"
  // would both produce "Add-Ons-Foo.md". Cheap to verify.
  const seen = new Map();
  for (const [src, dst] of renames) {
    if (seen.has(dst)) {
      console.error(`Name collision: ${src} and ${seen.get(dst)} both map to ${dst}`);
      process.exit(1);
    }
    seen.set(dst, src);
  }

  const rewrite = buildRewriter(renames);
  const prepared = [];
  const allFindings = [];

  for (const src of sources) {
    const raw = await readFile(join(DOCS_DIR, src), "utf8");
    const rewritten = rewrite(raw, src);
    const wikiName = renames.get(src);
    const withMarker = `${GENERATED_MARKER}\n\n${rewritten}`;
    const findings = scanContent(`wiki/${wikiName}`, withMarker);
    if (findings.length > 0) allFindings.push(...findings);
    prepared.push({ src, wikiName, content: withMarker });
  }

  if (allFindings.length > 0) {
    console.error(`OSINT scan found ${allFindings.length} issue(s). Halting — fix the source docs in docs/ and re-run.`);
    console.error("");
    for (const f of allFindings) {
      console.error(`  [${f.layer}] ${f.file}: ${f.detail}`);
    }
    process.exit(1);
  }

  console.log(`Sources: ${sources.length} files under docs/`);
  console.log(`Excluded prefixes: ${EXCLUDE_PREFIXES.join(", ")}`);
  console.log(`Wiki dir: ${args.wikiDir}`);
  console.log("");
  console.log("Plan (source -> wiki page):");
  for (const { src, wikiName } of prepared) {
    console.log(`  ${src}  ->  ${wikiName}`);
  }
  console.log("");

  if (args.dryRun) {
    console.log("Dry run — no files written.");
    return;
  }

  await mkdir(args.wikiDir, { recursive: true });
  for (const { wikiName, content } of prepared) {
    await writeFile(join(args.wikiDir, wikiName), content, "utf8");
  }

  console.log(`Wrote ${prepared.length} pages to ${args.wikiDir}`);
  console.log("");
  console.log("Next steps:");
  console.log(`  cd "${args.wikiDir}"`);
  console.log("  git status                          # review changes");
  console.log("  git diff                            # inspect rewrites");
  console.log('  git add -A && git commit -m "Sync wiki from docs/"');
  console.log("  git push");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
