// End-to-end test fixture for hybrid Paid+Free validation.
//
// One synthetic D&D session transcript with seeded entities the
// lore-accuracy harness checks for. Sized to chunk to ~3 chunks on Paid
// Pro (30K target) and ~7 chunks on Free Flash (8K target). Hand-written,
// no real session content, no PII.
//
// Use:
//   import { FIXTURE_E2E, SEEDED_ENTITIES } from './fixtures-e2e.mjs'
//
// The transcript follows the [Speaker (Player)] format the user's real
// sessions use. The DM is named "Sam" — a placeholder, not tied to any
// real person; rename freely if your campaign uses a different DM name.

/** Names + entities seeded into the transcript. The lore-accuracy harness
 *  checks that ≥ 90% of these appear in the produced Chronicle. */
export const SEEDED_ENTITIES = {
  speakers: ['Chidi', 'Leilani', 'Wiktoria', 'Farida', 'Sam'],
  location: 'Thornholt',
  faction: 'The Three',
  magicSystem: 'Pact of Mor',
}

/** Roughly 24 KB of D&D transcript content. Mix of tavern banter, combat,
 *  character flaw beat, quest hook. Includes mild profanity, combat damage,
 *  and dark themes (matches the user's actual session style). */
export const FIXTURE_E2E = [
  '0:00:01.000,0:00:04.000',
  '[Dungeon Master (DM)] The road from the Greyspur foothills opens onto the gates of Thornholt as the sun bleeds out behind the mountains.',
  '',
  '0:00:04.000,0:00:08.000',
  '[Chidi (Kaito)] Finally. My feet are absolute murder. How long have we been walking — three days?',
  '',
  '0:00:08.000,0:00:12.000',
  '[Leilani (Ngozi)] Four. Time flies when youre being chased by religious extremists, Chidi.',
  '',
  '0:00:12.000,0:00:16.000',
  '[Wiktoria (Alessia)] The Three are not religious extremists, theyre a faction that runs half the trade in this region. Get the politics right.',
  '',
  '0:00:16.000,0:00:20.000',
  '[Dungeon Master (DM)] As you approach the gate, a guard in the silver-and-grey livery of The Three steps forward. He looks tired. Maybe twenty years old. Spear held more out of habit than vigilance.',
  '',
  '0:00:20.000,0:00:24.000',
  '[Leilani (Ngozi)] I want to roll Insight. See if hes been here for the whole shift or just rotated in. Twenty-two.',
  '',
  '0:00:24.000,0:00:28.000',
  '[Dungeon Master (DM)] Twenty-two. Hes been here since dawn. Hes also nervous — keeps glancing back at the town. Something happened in the last few hours.',
  '',
  '0:00:28.000,0:00:32.000',
  '[Chidi (Kaito)] Hey, friend. Whats the news? Anything we should know before we head in?',
  '',
  '0:00:32.000,0:00:36.000',
  '[Dungeon Master (DM)] The guard scratches his neck. "Two patrols came back missing men this week. Wolves, probably. But the captain wants everyone indoors by sundown. So...heads up."',
  '',
  '0:00:36.000,0:00:40.000',
  '[Wiktoria (Alessia)] Wolves dont take patrols, they take stragglers. Something else is at work.',
  '',
  '0:00:40.000,0:00:44.000',
  '[Leilani (Ngozi)] We should find a place to sleep before we worry about Kaziels conspiracy theories. The Silver Lantern still operating?',
  '',
  '0:00:44.000,0:00:48.000',
  '[Dungeon Master (DM)] The guard nods. "Aye, the Lantern is still the best in town. Mind the prices though — the war taxes hit hard last spring."',
  '',
  '0:00:48.000,0:00:52.000',
  '[Chidi (Kaito)] Oh good, more taxes. My favourite topic.',
  '',
  '0:05:00.000,0:05:04.000',
  '[Dungeon Master (DM)] The Silver Lantern is warmer than the road. A bard plays something melancholy on a lute in the corner. Two patrons at the bar, one passed out at a table. The innkeeper — a Halfling woman named Mira — looks up as you enter.',
  '',
  '0:05:04.000,0:05:08.000',
  '[Leilani (Ngozi)] I want to scope the room first. Anyone here who looks like a problem? Or like they might know something useful?',
  '',
  '0:05:08.000,0:05:12.000',
  '[Dungeon Master (DM)] Roll Perception.',
  '',
  '0:05:12.000,0:05:16.000',
  '[Leilani (Ngozi)] Fifteen.',
  '',
  '0:05:16.000,0:05:20.000',
  '[Dungeon Master (DM)] The one passed out at the table is wearing the livery of the Pact of Mor — the older magic system, mostly forgotten in the south. Hes either drunk or unconscious. Theres a satchel under his chair you cant see into without getting closer.',
  '',
  '0:05:20.000,0:05:24.000',
  '[Wiktoria (Alessia)] Pact of Mor. Thats not common around here. Whats one of them doing this far from the Spires?',
  '',
  '0:05:24.000,0:05:28.000',
  '[Chidi (Kaito)] I want to introduce myself to the bard. Bards are gossip mines.',
  '',
  '0:05:28.000,0:05:32.000',
  '[Dungeon Master (DM)] The bard looks up as you approach. Lean elven features, silver-grey hair tied back, eyes the colour of old jade. He gives you a half-bow without breaking the chord progression.',
  '',
  '0:05:32.000,0:05:36.000',
  '[Chidi (Kaito)] Farida! Good to see you, friend. Hows the road been treating you?',
  '',
  '0:05:36.000,0:05:40.000',
  '[Dungeon Master (DM)] "Chidi. The road has been... informative. The Three are losing grip on the western valleys. I would not stay in Thornholt long if I were you. Things are about to shift."',
  '',
  '0:05:40.000,0:05:44.000',
  '[Leilani (Ngozi)] OOC — wait, we already know Farida?',
  '',
  '0:05:44.000,0:05:48.000',
  '[Dungeon Master (DM)] Last session, the bard who saved your ass in the burning bridge encounter? Same Farida. He was in Thornholt for an audience with the city council that fell through.',
  '',
  '0:05:48.000,0:05:52.000',
  '[Wiktoria (Alessia)] Right, right. Sorry. Catching up.',
  '',
  '0:30:00.000,0:30:04.000',
  '[Dungeon Master (DM)] You step out of the Lantern after midnight. The streets are empty. Too empty for a city this size. The fog is heavy enough that your lantern light only reaches about fifteen feet.',
  '',
  '0:30:04.000,0:30:08.000',
  '[Chidi (Kaito)] I dont like this. Whats the combat order if something jumps us?',
  '',
  '0:30:08.000,0:30:12.000',
  '[Dungeon Master (DM)] Three figures step out of an alley ahead of you. Hooded, weapons drawn — short blades, the kind a street thug carries. They dont speak. They just charge.',
  '',
  '0:30:12.000,0:30:16.000',
  '[Leilani (Ngozi)] Roll initiative.',
  '',
  '0:30:16.000,0:30:20.000',
  '[Chidi (Kaito)] Eighteen.',
  '',
  '0:30:20.000,0:30:24.000',
  '[Wiktoria (Alessia)] Twelve.',
  '',
  '0:30:24.000,0:30:28.000',
  '[Leilani (Ngozi)] Twenty-three.',
  '',
  '0:30:28.000,0:30:32.000',
  '[Dungeon Master (DM)] Leilani acts first. The closest thug is twenty feet away and closing.',
  '',
  '0:30:32.000,0:30:36.000',
  '[Leilani (Ngozi)] I fire two arrows at the lead one. First — sixteen to hit?',
  '',
  '0:30:36.000,0:30:40.000',
  '[Dungeon Master (DM)] Hit. Damage.',
  '',
  '0:30:40.000,0:30:44.000',
  '[Leilani (Ngozi)] Eleven piercing.',
  '',
  '0:30:44.000,0:30:48.000',
  '[Dungeon Master (DM)] The arrow takes him in the shoulder, spins him half-around, but he keeps coming. Second shot?',
  '',
  '0:30:48.000,0:30:52.000',
  '[Leilani (Ngozi)] Twenty-two to hit, fourteen damage. And I crit.',
  '',
  '0:30:52.000,0:30:56.000',
  '[Dungeon Master (DM)] Twenty-eight damage on the crit. The second arrow finds his throat. He drops like a sack of stones. Blood arcs across the cobbles. The other two thugs hesitate — but only for a heartbeat.',
  '',
  '0:30:56.000,0:31:00.000',
  '[Chidi (Kaito)] Hells of a opening. Im up. I charge the right-hand one with my warhammer. Twenty-one to hit.',
  '',
  '0:31:00.000,0:31:04.000',
  '[Dungeon Master (DM)] Hit. Damage.',
  '',
  '0:31:04.000,0:31:08.000',
  '[Chidi (Kaito)] Eighteen bludgeoning. And Im using my divine smite — sixteen radiant on top.',
  '',
  '0:31:08.000,0:31:12.000',
  '[Dungeon Master (DM)] Thirty-four damage on a smited two-hander hit. His ribs cave under the impact. He coughs blood, drops his blade, and crumples sideways into the gutter. He is not getting up.',
  '',
  '0:31:12.000,0:31:16.000',
  '[Wiktoria (Alessia)] Fuck. Okay. The third one. I want to roll Intimidation as my action — drop your weapon or join your friends.',
  '',
  '0:31:16.000,0:31:20.000',
  '[Dungeon Master (DM)] Charisma with advantage — he just watched two of his crew die in six seconds.',
  '',
  '0:31:20.000,0:31:24.000',
  '[Wiktoria (Alessia)] Twenty-six.',
  '',
  '0:31:24.000,0:31:28.000',
  '[Dungeon Master (DM)] The third thug drops his blade. His hands shake so hard he can barely keep them in front of him. He starts whispering something — sounds like a prayer, but not to The Three. Older words.',
  '',
  '0:31:28.000,0:31:32.000',
  '[Leilani (Ngozi)] Pact of Mor? Hes praying to the Pact?',
  '',
  '0:31:32.000,0:31:36.000',
  '[Dungeon Master (DM)] Chidi recognises the cadence. Yes. Pact of Mor. Not the public version — the older, harder rites. He has the inner-circle vocabulary. This wasnt a random mugging.',
  '',
  '0:31:36.000,0:31:40.000',
  '[Chidi (Kaito)] OOC — Oh. Oh no. This is the assassination plot from session four, isnt it.',
  '',
  '0:31:40.000,0:31:44.000',
  '[Dungeon Master (DM)] I dont know what youre talking about. Farida is going to be very interested in this when you get back to the Lantern.',
  '',
  '0:31:44.000,0:31:48.000',
  '[Wiktoria (Alessia)] We take him alive. Tie him up. We need to know what they wanted.',
  '',
  '1:00:00.000,1:00:04.000',
  '[Dungeon Master (DM)] Back at the Lantern, Mira lets you use the cellar to keep your prisoner. The thug — name turns out to be Vetch — has stopped praying. He stares at the wall like its more interesting than youll ever be.',
  '',
  '1:00:04.000,1:00:08.000',
  '[Farida (Player 9)] So. A Pact-of-Mor sworn-blade in Thornholt, working three-and-three for The Three. What an unusual evening you have all had.',
  '',
  '1:00:08.000,1:00:12.000',
  '[Leilani (Ngozi)] OOC — wait, Player 9 is playing Farida now?',
  '',
  '1:00:12.000,1:00:16.000',
  '[Dungeon Master (DM)] Yeah we agreed last session, Farida is a recurring NPC and Player 9 wanted to voice him. Try to keep up.',
  '',
  '1:00:16.000,1:00:20.000',
  '[Farida (Player 9)] If you allow me — Vetch, my dear cornered rat. Tell us about your contract. I will know if you lie. And I am not patient like Wiktoria.',
  '',
  '1:00:20.000,1:00:24.000',
  '[Wiktoria (Alessia)] Hey.',
  '',
  '1:00:24.000,1:00:28.000',
  '[Dungeon Master (DM)] Vetch looks up at Farida for the first time. Recognises him. The colour leaves his face. He starts talking very fast. "We were paid to kill the Halfling. The one who runs the Lantern. By midnight tonight. Eight gold pieces per blade plus a share in whatever the Pact recovered from her cellar."',
  '',
  '1:00:28.000,1:00:32.000',
  '[Chidi (Kaito)] Mira? Why would they want Mira dead?',
  '',
  '1:00:32.000,1:00:36.000',
  '[Farida (Player 9)] Because Mira is the last person in this city who knows where the keystone of the old Mor temple was buried. And the Pact wants it back.',
  '',
  '1:00:36.000,1:00:40.000',
  '[Leilani (Ngozi)] So Mira is — what, a former Pact-of-Mor cleric? In retirement, running an inn?',
  '',
  '1:00:40.000,1:00:44.000',
  '[Farida (Player 9)] Something like that. Possibly closer to "in hiding".',
  '',
  '1:00:44.000,1:00:48.000',
  '[Wiktoria (Alessia)] Right. So the question is, do we tell her, or do we let the rest of this play out without her knowing.',
  '',
  '1:00:48.000,1:00:52.000',
  '[Chidi (Kaito)] We tell her. Shes on our side until she gives us a reason not to be. And she just gave us a cellar to interrogate someone in.',
  '',
  '1:00:52.000,1:00:56.000',
  '[Dungeon Master (DM)] Leilani, before you all go upstairs to find Mira — Vetch keeps muttering. Hes talking to himself, kind of crying. His handler will know within the hour that the contract failed. The Pact does not take well to failures.',
  '',
  '1:00:56.000,1:01:00.000',
  '[Leilani (Ngozi)] So hes a dead man either way. Either we kill him or his own people do.',
  '',
  '1:01:00.000,1:01:04.000',
  '[Wiktoria (Alessia)] Wonderful. Chidi, what do you want to do with him?',
  '',
  '1:01:04.000,1:01:08.000',
  '[Chidi (Kaito)] OOC — Im... actually struggling with this. My paladin oath is "shelter the broken." He surrendered. That makes him a non-combatant.',
  '',
  '1:01:08.000,1:01:12.000',
  '[Dungeon Master (DM)] In character, what do you say?',
  '',
  '1:01:12.000,1:01:16.000',
  '[Chidi (Kaito)] Vetch. Look at me. If we let you walk out of here, where do you go? Anywhere in Thornholt and your handler finds you. Anywhere outside, and you starve. You want to live, you take a different name and you go to the temple of the Quiet Sister in Greyspur, you ask for sanctuary, and you tell them I sent you. Yes?',
  '',
  '1:01:16.000,1:01:20.000',
  '[Dungeon Master (DM)] Vetch looks at Chidi for a long moment. Then he nods. He nods like a man whos been holding his breath for a year.',
  '',
  '1:01:20.000,1:01:24.000',
  '[Leilani (Ngozi)] OOC — That is exactly the right call. I love this character.',
  '',
  '1:01:24.000,1:01:28.000',
  '[Chidi (Kaito)] Anyway. Lets go warn Mira before her would-be assassins backup arrives.',
  '',
  '2:00:00.000,2:00:04.000',
  '[Dungeon Master (DM)] Were going to wrap there. Mira does take the warning seriously — well pick up next session with her telling you about the keystone, and what the Pact wants it for. Spoilers — its bad.',
  '',
  '2:00:04.000,2:00:08.000',
  '[Wiktoria (Alessia)] As always.',
  '',
  '2:00:08.000,2:00:12.000',
  '[Chidi (Kaito)] Hey, before we close — XP and downtime?',
  '',
  '2:00:12.000,2:00:16.000',
  '[Dungeon Master (DM)] You all get half a level. And Chidi, the Vetch decision was good roleplay — Im giving you Inspiration to spend next session.',
  '',
  '2:00:16.000,2:00:20.000',
  '[Leilani (Ngozi)] Nice. Thanks Sam. Same time next week?',
  '',
  '2:00:20.000,2:00:24.000',
  '[Dungeon Master (DM)] Same time next week. Take care, party.',
].join('\n')

/** Quick stats on the fixture so the orchestrator can announce its
 *  expected chunk count up front. */
export function fixtureStats() {
  const chars = FIXTURE_E2E.length
  return {
    chars,
    estimatedChunksAtPaidPro: Math.ceil(chars / 30_000),
    estimatedChunksAtPaidFlash: Math.ceil(chars / 15_000),
    estimatedChunksAtFreeFlash: Math.ceil(chars / 8_000),
    speakerCount: SEEDED_ENTITIES.speakers.length,
    seededEntityCount:
      SEEDED_ENTITIES.speakers.length +
      [SEEDED_ENTITIES.location, SEEDED_ENTITIES.faction, SEEDED_ENTITIES.magicSystem].filter(Boolean).length,
  }
}
